//  ___FILEHEADER___

protocol ___FILEBASENAMEASIDENTIFIER___Protocol {
  
}

final class ___FILEBASENAMEASIDENTIFIER___: Presenter {
  
}

// MARK: ___FILEBASENAMEASIDENTIFIER___Protocol
extension ___FILEBASENAMEASIDENTIFIER___: ___FILEBASENAMEASIDENTIFIER___Protocol {

}