# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MercadoPagoSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MercadoPagoSDK
  pod 'MLUI'
  pod 'MLCardDrawer'
  pod 'MLBusinessComponents'
  pod 'MLCardForm'
  pod 'AndesUI/AndesBottomSheet'

  target 'SDKTests' do
    # Pods for testing
  end

end
